# Text Classification

## Get a Dataset

In [1]:
# !pip install transformers datasets evaluate

Dataset used: https://huggingface.co/datasets/disaster_response_messages

In [1]:
from datasets import load_dataset
dataset = load_dataset('disaster_response_messages')
dataset['train'][0:5]

Found cached dataset disaster_response_messages (C:/Users/diego/.cache/huggingface/datasets/disaster_response_messages/default/0.0.0/9817bca311ab712ad30f55c4f3563c88db15fe240c645f51dcb96f5d0f7dfda4)


  0%|          | 0/3 [00:00<?, ?it/s]

{'split': ['train', 'train', 'train', 'train', 'train'],
 'message': ['Weather update - a cold front from Cuba that could pass over Haiti',
  'Is the Hurricane over or is it not over',
  'says: west side of Haiti, rest of the country today and tonight',
  'Information about the National Palace-',
  'Storm at sacred heart of jesus'],
 'original': ['Un front froid se retrouve sur Cuba ce matin. Il pourrait traverser Haiti demain. Des averses de pluie isolee sont encore prevues sur notre region ce soi',
  'Cyclone nan fini osinon li pa fini',
  'facade ouest d Haiti et le reste du pays aujourd hui et ce soir',
  'Informtion au nivaux palais nationl',
  'Cyclone Coeur sacr de jesus'],
 'genre': ['direct', 'direct', 'direct', 'direct', 'direct'],
 'related': [1, 1, 1, 0, 1],
 'PII': [0, 0, 0, 0, 0],
 'request': [0, 0, 0, 0, 0],
 'offer': [0, 0, 0, 0, 0],
 'aid_related': [0, 1, 0, 0, 0],
 'medical_help': [0, 0, 0, 0, 0],
 'medical_products': [0, 0, 0, 0, 0],
 'search_and_rescue': [0, 0, 0, 0

In [2]:
dataset

DatasetDict({
    train: Dataset({
        features: ['split', 'message', 'original', 'genre', 'related', 'PII', 'request', 'offer', 'aid_related', 'medical_help', 'medical_products', 'search_and_rescue', 'security', 'military', 'child_alone', 'water', 'food', 'shelter', 'clothing', 'money', 'missing_people', 'refugees', 'death', 'other_aid', 'infrastructure_related', 'transport', 'buildings', 'electricity', 'tools', 'hospitals', 'shops', 'aid_centers', 'other_infrastructure', 'weather_related', 'floods', 'storm', 'fire', 'earthquake', 'cold', 'other_weather', 'direct_report'],
        num_rows: 21046
    })
    test: Dataset({
        features: ['split', 'message', 'original', 'genre', 'related', 'PII', 'request', 'offer', 'aid_related', 'medical_help', 'medical_products', 'search_and_rescue', 'security', 'military', 'child_alone', 'water', 'food', 'shelter', 'clothing', 'money', 'missing_people', 'refugees', 'death', 'other_aid', 'infrastructure_related', 'transport', 'buildings', 'e

In [67]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("bert-base-cased")


def tokenize_function(examples):
    return tokenizer(examples["message"], padding="max_length", truncation=True, return_tensors='np')


tokenized_datasets = dataset.map(tokenize_function, batched=True)

loading configuration file config.json from cache at C:\Users\diego/.cache\huggingface\hub\models--bert-base-cased\snapshots\5532cc56f74641d4bb33641f5c76a55d11f846e0\config.json
Model config BertConfig {
  "_name_or_path": "bert-base-cased",
  "architectures": [
    "BertForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.25.1",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 28996
}

loading file vocab.txt from cache at C:\Users\diego/.cache\huggingface\hub\models--bert-base-cased\snapshots\5532cc56f74641d4bb33641f5c76a55d11f846e0\vocab.txt
loa

  0%|          | 0/3 [00:00<?, ?ba/s]

In [31]:
tokenized_datasets["train"]

Dataset({
    features: ['split', 'message', 'original', 'genre', 'related', 'PII', 'request', 'offer', 'aid_related', 'medical_help', 'medical_products', 'search_and_rescue', 'security', 'military', 'child_alone', 'water', 'food', 'shelter', 'clothing', 'money', 'missing_people', 'refugees', 'death', 'other_aid', 'infrastructure_related', 'transport', 'buildings', 'electricity', 'tools', 'hospitals', 'shops', 'aid_centers', 'other_infrastructure', 'weather_related', 'floods', 'storm', 'fire', 'earthquake', 'cold', 'other_weather', 'direct_report', 'input_ids', 'token_type_ids', 'attention_mask'],
    num_rows: 21046
})

In [32]:
tokenizer.decode(tokenized_datasets["train"][0]['input_ids'])

'[CLS] Weather update - a cold front from Cuba that could pass over Haiti [SEP] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [P

In [33]:
tokenizer('Weather update - a cold front from Cuba that could pass over Haiti')

{'input_ids': [101, 14263, 11984, 118, 170, 2504, 1524, 1121, 6881, 1115, 1180, 2789, 1166, 13364, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

In [34]:
i_ids = tokenized_datasets["train"][0:10]['aid_related']
print(i_ids)
len(i_ids)

[0, 1, 0, 0, 0, 1, 0, 1, 0, 1]


10

In [35]:
tokenized_datasets.set_format('torch')
tokenized_datasets["train"][0:10]['aid_related']

tensor([0, 1, 0, 0, 0, 1, 0, 1, 0, 1])

In [53]:
small_train_dataset = tokenized_datasets["train"].shuffle(seed=42).select(range(4000)).rename_column("aid_related", "labels")
small_test_dataset = tokenized_datasets["test"].shuffle(seed=42).select(range(2000)).rename_column("aid_related", "labels")

Loading cached shuffled indices for dataset at C:\Users\diego\.cache\huggingface\datasets\disaster_response_messages\default\0.0.0\9817bca311ab712ad30f55c4f3563c88db15fe240c645f51dcb96f5d0f7dfda4\cache-1811067f9eccfdd1.arrow
Loading cached shuffled indices for dataset at C:\Users\diego\.cache\huggingface\datasets\disaster_response_messages\default\0.0.0\9817bca311ab712ad30f55c4f3563c88db15fe240c645f51dcb96f5d0f7dfda4\cache-40a728878dcafa20.arrow


In [55]:
X_train, Y_train = small_train_dataset['input_ids'], small_train_dataset['labels']
X_test, Y_test = small_test_dataset['input_ids'], small_test_dataset['labels']

## BOW + XGBoost as Baseline

Resources: 

* https://www.projectpro.io/recipes/use-xgboost-classifier-and-regressor-in-python#mcetoc_1g1ql3am48
* https://xgboost.readthedocs.io/en/stable/tutorials/model.html

In [30]:
# !pip install install xgboost

In [56]:
import xgboost as xgb

tree_model = xgb.XGBClassifier(n_estimators=40)
tree_model.fit(X_train, Y_train)

XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, feature_types=None, gamma=0, gpu_id=-1,
              grow_policy='depthwise', importance_type=None,
              interaction_constraints='', learning_rate=0.300000012,
              max_bin=256, max_cat_threshold=64, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimators=40, n_jobs=0,
              num_parallel_tree=1, predictor='auto', random_state=0, ...)

In [57]:
# Metrics for the train set

from sklearn import metrics

predicted_y = tree_model.predict(X_train)
print(metrics.classification_report(Y_train, predicted_y))
print(metrics.confusion_matrix(Y_train, predicted_y))

              precision    recall  f1-score   support

           0       0.91      0.99      0.95      2362
           1       0.99      0.87      0.92      1638

    accuracy                           0.94      4000
   macro avg       0.95      0.93      0.94      4000
weighted avg       0.94      0.94      0.94      4000

[[2343   19]
 [ 221 1417]]


In [58]:
# Metrics for the test set

predicted_y = tree_model.predict(X_test)
print(metrics.classification_report(Y_test, predicted_y))
print(metrics.confusion_matrix(Y_test, predicted_y))

              precision    recall  f1-score   support

           0       0.61      0.74      0.67      1135
           1       0.52      0.38      0.44       865

    accuracy                           0.58      2000
   macro avg       0.57      0.56      0.55      2000
weighted avg       0.57      0.58      0.57      2000

[[835 300]
 [534 331]]


In [59]:
# lets see how it does for the whole test dataset
X_test, Y_test = tokenized_datasets["test"]['input_ids'], tokenized_datasets["test"]['aid_related']
predicted_y = tree_model.predict(X_test)
print(metrics.classification_report(Y_test, predicted_y))
print(metrics.confusion_matrix(Y_test, predicted_y))

              precision    recall  f1-score   support

           0       0.61      0.74      0.67      1484
           1       0.53      0.38      0.45      1145

    accuracy                           0.59      2629
   macro avg       0.57      0.56      0.56      2629
weighted avg       0.58      0.59      0.57      2629

[[1099  385]
 [ 705  440]]


## Fine Tunning for Text Classification

### HugginFace APIs

https://huggingface.co/docs/transformers/training

In [68]:
from transformers import AutoModelForSequenceClassification

# model = AutoModelForSequenceClassification.from_pretrained("bert-base-cased", num_labels=2)
model = AutoModelForSequenceClassification.from_pretrained("prajjwal1/bert-mini", num_labels=2)

Downloading:   0%|          | 0.00/286 [00:00<?, ?B/s]

c:\Users\diego\anaconda3\envs\dl_arch_env\lib\site-packages\huggingface_hub\file_download.py:127: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\diego\.cache\huggingface\hub. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to see activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
loading configuration file config.json from cache at C:\Users\diego/.cache\huggingface\hub\models--prajjwal1--bert-mini\snapshots\5e

Downloading:   0%|          | 0.00/45.1M [00:00<?, ?B/s]

loading weights file pytorch_model.bin from cache at C:\Users\diego/.cache\huggingface\hub\models--prajjwal1--bert-mini\snapshots\5e123abc2480f0c4b4cac186d3b3f09299c258fc\pytorch_model.bin
Some weights of the model checkpoint at prajjwal1/bert-mini were not used when initializing BertForSequenceClassification: ['cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.weight', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.bias', 'cls.predictions.decoder.weight', 'cls.predictions.bias', 'cls.predictions.decoder.bias', 'cls.predictions.transform.LayerNorm.bias']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you 

In [69]:
import numpy as np
import evaluate

metric = evaluate.load("accuracy")

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    return metric.compute(predictions=predictions, references=labels)

In [70]:
from transformers import TrainingArguments, Trainer

#  no_cuda
training_args = TrainingArguments(output_dir="./outputs", disable_tqdm=False , 
                                    evaluation_strategy='epoch', per_device_train_batch_size=4, 
                                    gradient_accumulation_steps=2)

PyTorch: setting up devices
The default value for the training argument `--report_to` will change in v5 (from all installed integrations to none). In v5, you will need to use `--report_to all` to get the same behavior as now. You should start updating your code and make this info disappear :-).


In [71]:
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=small_train_dataset,
    eval_dataset=small_test_dataset,
    compute_metrics=compute_metrics,
)

In [72]:
trainer.train()

The following columns in the training set don't have a corresponding argument in `BertForSequenceClassification.forward` and have been ignored: food, other_weather, original, offer, medical_help, hospitals, military, missing_people, clothing, money, search_and_rescue, storm, cold, security, other_aid, death, shops, transport, weather_related, message, child_alone, earthquake, split, electricity, direct_report, request, refugees, aid_centers, buildings, tools, genre, other_infrastructure, fire, PII, floods, related, medical_products, water, shelter, infrastructure_related. If food, other_weather, original, offer, medical_help, hospitals, military, missing_people, clothing, money, search_and_rescue, storm, cold, security, other_aid, death, shops, transport, weather_related, message, child_alone, earthquake, split, electricity, direct_report, request, refugees, aid_centers, buildings, tools, genre, other_infrastructure, fire, PII, floods, related, medical_products, water, shelter, infrast

  0%|          | 0/1500 [00:00<?, ?it/s]